# Kesh — Messages English (Switzerland)

# Authentication errors
error-invalid-credentials = Invalid credentials
error-unauthenticated = Not authenticated
error-invalid-refresh-token = Session expired
error-rate-limited = Too many attempts

# Authorization errors
error-forbidden = Access denied
error-api-key-read-only = This API key is read-only (scope "read"). Only GET requests are allowed.
error-api-key-management-forbidden = API key management is not allowed via an API key. Use the web interface.
error-cannot-disable-self = Cannot disable your own account
error-cannot-disable-last-admin = Cannot disable the last administrator

# Resource errors
error-not-found = Resource not found
error-conflict = Resource already exists
error-optimistic-lock = Version conflict — the resource has been modified
error-foreign-key = Invalid reference
error-journal-entry-linked-to-invoice = This journal entry was generated by a validated invoice and cannot be deleted directly. Cancel the related invoice first.
error-check-constraint = Invalid value
error-illegal-state = Illegal state transition

# Validation errors
error-validation = Validation error
error-email-invalid = Invalid email format
error-username-empty = Username cannot be empty
error-username-too-long = Username must not exceed { $max } characters
error-username-contains-at = Username must not contain the “@” character
error-email-template-unknown-variables = The template contains unknown variables

# System errors
error-internal = Internal error
error-service-unavailable = Service temporarily unavailable
db-unavailable-banner = Database temporarily unavailable — retrying automatically

# Onboarding errors (Story 2.2)
error-onboarding-step-already-completed = This configuration step has already been completed

# Onboarding — wizard
onboarding-choose-mode = Choose your usage mode
onboarding-mode-guided = Guided
onboarding-mode-guided-desc = Generous spacing, contextual help, confirmations before actions
onboarding-mode-expert = Expert
onboarding-mode-expert-desc = Compact interface, keyboard shortcuts, direct actions
onboarding-choose-path = How would you like to start?
onboarding-path-demo = Explore with demo data
onboarding-path-demo-desc = Discover Kesh with realistic sample data
onboarding-path-production = Set up for production
onboarding-path-production-desc = Configure your organisation to start working

# Demo banner
demo-banner-text = Demo instance — fictitious data
demo-banner-reset = Reset for production
demo-reset-confirm-title = Reset instance
demo-reset-confirm-body = All demo data will be deleted. Do you want to continue?
demo-reset-confirm-ok = Confirm
demo-reset-confirm-cancel = Cancel

# Navigation sidebar (Story 6.3 + v014-1)
nav-home = Home
nav-contacts = Contacts
nav-products = Catalog
nav-invoices = Invoices
nav-supplier-invoices = Supplier invoices
nav-payment-batches = Supplier payments
nav-invoicing-due-dates = Due Dates
nav-invoicing-reminders = Reminders
nav-settings = Settings
# Story v014-1 — restructuration sidebar
nav-quotidien = Daily
nav-mensuel = Monthly
nav-administration = Administration
nav-accounts = Chart of accounts
nav-fiscal-years = Fiscal years
nav-opening-balances = Opening balances
nav-bank-accounts = Bank accounts
nav-bank-profiles = Bank profiles
nav-reconciliation-rules = Reconciliation rules

# Onboarding — Path B (Story 2.3)
onboarding-choose-org-type = Organisation type
onboarding-org-independant = Independent
onboarding-org-independant-desc = Self-employed, freelancer
onboarding-org-association = Association
onboarding-org-association-desc = Non-profit association
onboarding-org-pme = SME
onboarding-org-pme-desc = Small and medium enterprise (Ltd, LLC)
onboarding-choose-accounting-lang = Accounting language
onboarding-accounting-lang-desc = Language of chart of accounts labels (independent of interface language)
onboarding-coordinates-title = Your organisation details
onboarding-field-name = Name / Company name
onboarding-field-address = Address
onboarding-field-ide = UID number
onboarding-field-ide-hint = optional, format CHE-xxx.xxx.xxx
onboarding-bank-title = Primary bank account
onboarding-field-bank-name = Bank name
onboarding-field-iban = IBAN
onboarding-field-qr-iban = QR-IBAN
onboarding-skip-bank = Configure later
onboarding-next = Continue
onboarding-stub-name-notice = Your company has a provisional name — complete your details
incomplete-banner-text = Configuration incomplete — Complete setup
incomplete-banner-cta = Complete setup

# Homepage (Story 2.4)
homepage-title = Dashboard
homepage-entries-title = Recent entries
homepage-entries-empty = No entries.
homepage-entries-empty-guided = No entries yet. Start by recording your first journal entry.
homepage-entries-action = Record an entry
homepage-invoices-title = Open invoices
homepage-invoices-empty = No open invoices.
homepage-invoices-empty-guided = No open invoices. Create your first invoice to bill your clients.
homepage-invoices-action = Create an invoice
homepage-reminders-count = { $n } invoice(s) to follow up
homepage-bank-title = Bank accounts
homepage-bank-empty = No bank account.
homepage-bank-empty-guided = No bank account configured. Add your account to import statements.
homepage-bank-no-transactions = No imported transactions
homepage-bank-action = Configure

# Settings (Story 2.4)
settings-title = Settings
settings-org-title = Organisation
settings-accounting-title = Accounting
settings-bank-title = Bank accounts
settings-users-title = Users
settings-field-name = Name
settings-field-address = Address
settings-field-ide = UID
settings-field-org-type = Organisation type
settings-field-instance-language = Interface language
settings-field-accounting-language = Accounting language
search-coming-soon = Search coming soon

# Misc i18n (Story 2.4 review)
loading = Loading...
settings-edit = Edit
settings-edit-coming-soon = Editing coming soon
settings-manage = Manage
settings-no-bank = No bank account configured.
settings-no-company = No organisation configured. Complete onboarding first.

# Chart of Accounts (Story 3.1)
accounts-title = Chart of accounts
accounts-add = New account
accounts-edit = Edit account
accounts-archive = Archive
accounts-archive-confirm = The account will no longer be available in future selections, but will remain visible in existing entries.
account-field-number = Number
account-field-name = Name
account-field-type = Type
account-field-parent = Parent account
account-type-asset = Asset
account-type-liability = Liability
account-type-revenue = Revenue
account-type-expense = Expense
account-archived-label = Archived
# --- Story 14-3a: account roles & postability ---
account-field-role = Role
account-role-none = None
account-role-receivable = Trade receivables
account-role-default-revenue = Default revenue
account-role-payable = Trade payables
account-role-vat-recoverable = Input VAT
account-role-vat-payable = VAT payable
account-role-vat-settlement = VAT settlement
account-role-equity-capital = Capital
account-role-equity-other = Other equity
account-role-retained-earnings = Retained earnings
account-role-current-year-result = Current year result
account-role-archived-hint = Role inactive — this account is archived
account-field-postable = Postable
account-postable-no = Not postable
account-postable-hint = A non-postable account does not accept manual journal entry input
accounts-reactivate-aria = Reactivate account { $number }
accounts-reactivated = Account { $number } reactivated
accounts-role-conflict = The role is already assigned to account { $number } — { $name }. Remove it from that account first.
accounts-error-number-required = Number is required.
accounts-error-name-required = Name is required.
accounts-error-number-exists = This account number already exists.
accounts-error-stale = This page is out of date. Reload it and try again.
accounts-created = Account { $number } created
accounts-updated = Account { $number } updated
accounts-archived = Account { $number } archived
accounts-count = { $count } accounts
accounts-show-archived = Show archived accounts
# Story 14-3a — code review: dialog labels and role errors
accounts-create-description = Add an account to the chart of accounts.
accounts-edit-title = Edit account { $number }
accounts-edit-description = The number cannot be changed after creation.
accounts-archive-title = Archive account { $number }?
accounts-archiving = Archiving…
account-field-parent-optional = Parent account (optional)
accounts-parent-none = None
accounts-parent-archived = Parent account { $number } is archived. Reactivate it first.
accounts-role-invalid-for-type = The { $role } role cannot be assigned to a { $type } account.
accounts-role-conflict-generic = This role has just been assigned to another account. Please reload the page.
accounts-reactivate-without-role = Reactivate without the role
accounts-reactivate-without-role-description = This account's role has been taken over by another account. You can reactivate it without its role — it stays editable afterwards.
accounts-reactivating = Reactivating…
common-empty = No items found.
common-create = Create
common-creating = Creating…
common-saving = Saving…


# Mode Guided/Expert (Story 2.5)
mode-guided-label = Guided
mode-expert-label = Expert
shortcut-new-entry = Ctrl+N : New entry

# Journal entries (Story 3.2)
error-entry-unbalanced = Unbalanced entry — total debits ({ $debit }) does not match total credits ({ $credit })
error-no-fiscal-year = No fiscal year exists for date { $date }. Create a fiscal year before recording entries.
error-fiscal-year-closed = The fiscal year for date { $date } is closed — no entries can be added or modified (Swiss CO art. 957-964).
journal-entries-title = Journal entries
journal-entries-new = New entry
journal-entries-empty-list = No entries yet
journal-entries-col-number = No.
journal-entries-col-date = Date
journal-entries-col-journal = Journal
journal-entries-col-description = Description
journal-entries-col-total = Total
journal-entry-form-title = New journal entry
journal-entry-form-date = Date
journal-entry-form-journal = Journal
journal-entry-form-description = Description
journal-entry-form-add-line = + Add line
journal-entry-form-remove-line = Remove line
journal-entry-form-col-account = Account
journal-entry-form-col-debit = Debit
journal-entry-form-col-credit = Credit
journal-entry-form-total-debit = Total debits
journal-entry-form-total-credit = Total credits
journal-entry-form-diff = Difference
journal-entry-form-balanced = Balanced
journal-entry-form-unbalanced = Unbalanced
journal-entry-form-submit = Save
journal-entry-form-cancel = Cancel
journal-entry-form-incomplete-line = Incomplete line
journal-entry-form-max-decimals = Maximum 4 decimals
journal-entry-form-amount-too-large = Amount too large
account-autocomplete-unavailable = Autocomplete unavailable — enter account ID
journal-achats = Purchases
journal-ventes = Sales
journal-banque = Bank
journal-caisse = Cash
journal-od = Miscellaneous
journal-entry-saved = Entry saved
error-fiscal-year-closed-generic = The fiscal year is closed — no entries can be added or modified (Swiss CO art. 957-964).
error-inactive-accounts = One or more accounts are archived or invalid.

# Per-line revenue account (Story 16-1a, #152)
invoice-line-account-subject-line = Line { $line }
invoice-line-account-subject-default = the company default revenue account
invoice-line-account-unknown = { $subject }: the selected account does not exist or does not belong to this company
invoice-line-account-inactive = { $subject }: account { $number } is archived
invoice-line-account-not-revenue = { $subject }: account { $number } is not a revenue account
invoice-line-account-not-postable = { $subject }: account { $number } is not postable — pick another account
invoice-line-revenue-account-invalid = Invalid revenue account — { $detail }
credit-note-revenue-account-archived = Cannot issue the credit note — { $detail }. Reactivate the affected accounts.
invoice-error-total-zero = This invoice has a total amount of zero and cannot be validated. Add at least one line with a unit price greater than zero.
credit-note-error-total-zero = This invoice has a total amount of zero: no credit note can be issued.

# Edit & delete journal entries (Story 3.3)
journal-entry-edit = Edit
journal-entry-delete = Delete
journal-entry-delete-confirm-title = Delete entry No.{ $number }?
journal-entry-delete-confirm-message = This action is irreversible. The action will be recorded in the audit log.
journal-entry-delete-confirm-cancel = Cancel
journal-entry-delete-confirm-delete = Delete
journal-entry-deleted = Entry deleted
journal-entry-conflict-title = Version conflict
journal-entry-conflict-message = This entry has been modified by another user. Reload?
journal-entry-conflict-reload = Reload
journal-entry-conflict-reloaded = List reloaded — click Edit again to resume

# VAT purchase assistant (Story 18-1c)
vat-purchase-title = VAT purchase assistant
vat-purchase-config-required = Configure the input VAT account in Settings → Invoicing to use the assistant.
vat-purchase-no-rates = No VAT rate configured — see Settings → VAT rates.
vat-purchase-charge-account = Expense account
vat-purchase-ht = Amount excl. VAT
vat-purchase-rate = VAT rate
vat-purchase-rate-placeholder = Choose a rate
vat-purchase-counterparty = Counterparty account
vat-purchase-same-account = The expense account and counterparty must be different.
vat-purchase-recoverable-conflict = The expense account and counterparty cannot be the input VAT account.
vat-purchase-insert = Insert lines
vat-purchase-description = Purchase — VAT { $rate } % recoverable
vat-purchase-description-exempt = Purchase — no VAT
vat-purchase-replace-title = Replace draft?
vat-purchase-replace-message = Lines or a description have already been entered. Continuing will overwrite the current draft.
vat-purchase-replace-confirm = Replace
# VAT rate categories (reused by the VAT purchase assistant, Story 18-1c)
vat-category-normal = Standard rate
vat-category-reduced = Reduced rate
vat-category-special = Special rate (accommodation)
vat-category-exempt = Exempt / 0 %
vat-category-custom = Custom
error-date-outside-fiscal-year = The date { $date } is not within the current fiscal year of this entry
error-date-outside-fiscal-year-generic = The date is not within the current fiscal year of this entry

# Search, pagination, sorting (Story 3.4)
journal-entries-filter-description = Description
journal-entries-filter-amount-min = Amount min
journal-entries-filter-amount-max = Amount max
journal-entries-filter-date-from = From date
journal-entries-filter-date-to = To date
journal-entries-filter-journal = Journal
journal-entries-filter-journal-all = All
journal-entries-filter-reset = Reset
journal-entries-pagination-on = of
journal-entries-pagination-prev = Previous
journal-entries-pagination-next = Next
journal-entries-pagination-page-size = Per page
journal-entries-sort-asc-indicator = sorted ascending
journal-entries-sort-desc-indicator = sorted descending
journal-entries-loading = Loading…

# Bilingual tooltips for accounting terms (Story 3.5)
tooltip-debit-natural = Money comes into this account
tooltip-debit-technical = Debit — left column
tooltip-credit-natural = Money goes out from this account
tooltip-credit-technical = Credit — right column
tooltip-journal-natural = Register where similar entries are grouped
tooltip-journal-technical = Accounting journal (Purchases, Sales, Bank, Cash, Miscellaneous)
tooltip-balanced-natural = Total money in equals total money out
tooltip-balanced-technical = Double-entry balanced (debits = credits)

# Story 4.1 — Address book (contacts CRUD)
contacts-page-title = Address book
contact-form-create-title = New contact
contact-form-edit-title = Edit contact
contact-form-name = Name / Company name
contact-form-type = Type
contact-form-is-client = Client
contact-form-is-supplier = Supplier
contact-form-email = Email
contact-form-phone = Phone
contact-form-address = Address
contact-form-ide = UID number (CHE)
contact-form-ide-help = Format: CHE-123.456.789
contact-type-personne = Person
contact-type-entreprise = Company
contact-form-submit-create = Create
contact-form-submit-edit = Save
contact-form-cancel = Cancel
contact-list-new = New contact
contact-list-edit = Edit
contact-list-archive = Archive
contact-archive-confirm = Archive
contact-archive-cancel = Cancel
contact-col-name = Name
contact-col-type = Type
contact-col-flags = Roles
contact-col-ide = UID
contact-col-email = Email
contact-col-actions = Actions
contact-filter-search-placeholder = Search by name or email…
contact-filter-type-all = All types
contact-filter-archived = Include archived
contact-empty-list = No contacts. Create your first contact with the "New contact" button.
contact-created-success = Contact created
contact-updated-success = Contact updated
contact-archived-success = Contact archived
contact-archive-confirm-title = Archive contact?
contact-archive-confirm-body = The contact will no longer appear in the default list. You can still view it by enabling "Include archived".
contact-error-name-required = Name is required
contact-error-name-too-long = Name must be at most 255 characters
contact-error-email-invalid = Invalid email format
contact-error-ide-invalid = Invalid Swiss UID number (format or checksum)
contact-error-payment-terms-days-range = The payment terms must be a whole number between 0 and 365 days
contact-error-ide-duplicate = A contact with this UID number already exists
contact-error-not-found = Contact not found
contact-error-archived-no-modify = Contact archived — no further modification or archiving allowed
contact-conflict-title = Version conflict
contact-conflict-body = This contact has been modified elsewhere. Reload the current version?
error-ide-already-exists = A contact with this UID number already exists

# Story 4.2 — Payment terms & product catalog
contact-form-payment-terms = Payment terms
contact-form-payment-terms-placeholder = e.g. 30 days net
contact-payment-terms-days-label = { $days ->
    [one] Payable within { $days } day
   *[other] Payable within { $days } days
}
contact-payment-terms-immediate-label = Due upon receipt
contact-form-payment-terms-days = Payment terms (days)
contact-form-payment-terms-days-hint = Invoice due dates will be pre-calculated and the payment terms text generated automatically.
contact-form-payment-terms-disabled-hint = Text generated automatically from the payment terms in days.
products-page-title = Product / service catalog
product-form-create-title = New product
product-form-edit-title = Edit product
product-form-name = Name
product-form-description = Description
product-form-price = Unit price
product-form-vat-rate = VAT rate
product-form-vat-help = Swiss VAT rates effective from 01.01.2024
product-vat-exempt = 0.00% — Exempt
product-vat-reduced = 2.60% — Reduced rate
product-vat-special = 3.80% — Accommodation
product-vat-normal = 8.10% — Standard rate
product-list-new = New product
product-list-edit = Edit
product-list-archive = Archive
product-col-name = Name
product-col-description = Description
product-col-price = Price
product-col-vat = VAT
product-col-actions = Actions
product-filter-search = Search by name or description…
product-filter-archived = Include archived
product-empty-list = No products. Create your first product with the "New product" button.
product-created-success = Product created
product-updated-success = Product updated
product-archived-success = Product archived
product-error-name-required = Name is required
product-error-name-too-long = Name must be at most 255 characters
product-error-price-required = Price is required
product-error-price-negative = Price must be positive or zero
product-error-price-invalid = Invalid price format
product-error-vat-invalid = VAT rate not allowed
product-error-vat-loading = Loading VAT rates, please wait…
product-error-vat-fetch-failed = Unable to load VAT rates. Check your network connection and reload the page.
product-error-name-duplicate = A product with this name already exists
product-archive-confirm-title = Archive this product?
product-archive-confirm-body = The product will no longer be visible in the default list. You can still view it by enabling "Include archived".
product-conflict-title = Version conflict
product-conflict-body = This product was modified elsewhere. Do you want to reload the current version?
product-filter-reset = Reset
product-pagination-prev = Previous
product-pagination-next = Next
product-pagination-of = of
product-conflict-reload = Reload
product-form-cancel = Cancel
product-form-submit-create = Create
product-form-submit-edit = Save
product-archive-cancel = Cancel
product-archive-confirm = Archive

# --- Story 5.1: Draft invoices ---
invoices-page-title = Invoices
invoices-settings-vat-accounts-title = VAT accounts
invoices-settings-vat-accounts-hint = Accounts used for VAT bookkeeping (prepared for the FTA VAT settlement).
invoices-settings-vat-payable = VAT payable account (Liability)
invoices-settings-vat-recoverable = Recoverable VAT account (Asset)
invoices-settings-vat-decompte = VAT settlement account (Liability)
invoice-new-title = New invoice
invoice-edit-title = Edit invoice
invoice-view-title = Invoice
invoice-form-contact = Contact
invoice-form-date = Date
invoice-form-due-date = Due date
invoice-form-payment-terms = Payment terms
invoice-form-status = Status
invoice-form-number = Invoice no.
invoice-line-description = Description
invoice-line-quantity = Quantity
invoice-line-unit-price = Unit price
invoice-line-vat-rate = VAT %
invoice-line-total = Total
invoice-line-actions = Actions
invoice-add-free-line = Free line
invoice-add-from-catalog = From catalog
invoice-col-date = Date
invoice-col-contact = Contact
invoice-col-number = No.
invoice-col-status = Status
invoice-col-total = Total
invoice-col-actions = Actions
invoice-status-draft = Draft
invoice-status-validated = Validated
invoice-status-cancelled = Cancelled
invoice-filter-search = Search…
invoice-filter-status-all = All statuses
invoice-filter-contact-all = All contacts
invoice-filter-date-from = From
invoice-filter-date-to = To
# Story 21-6a (D10) — suspension des rappels : badge + filtre en liste factures.
invoice-paused-badge = Paused
invoice-paused-filter-label = Reminders
invoice-paused-filter-all = All
invoice-paused-filter-paused = Paused
invoice-paused-filter-not-paused = Active
invoice-new-button = New invoice
invoice-edit-button = Edit
invoice-delete-button = Delete
invoice-subtotal = Subtotal
invoice-total = Total
invoice-empty-list = No invoices. Create your first one via "New invoice".
invoice-created-success = Invoice created
invoice-updated-success = Invoice updated
invoice-deleted-success = Invoice deleted
invoice-delete-confirm-title = Delete invoice?
invoice-delete-confirm-body = This draft invoice will be permanently deleted.
invoice-conflict-title = Version conflict
invoice-conflict-body = This invoice was modified elsewhere. Reload current version?
invoice-error-no-lines = An invoice must contain at least one line
invoice-error-contact-required = Please select a contact
invoice-error-contact-invalid = Contact not found
invoice-error-quantity-positive = Quantity must be strictly positive
invoice-error-description-required = Description is required
invoice-error-vat-invalid = VAT rate not allowed. Accepted: 0.00%, 2.60%, 3.80%, 8.10%
invoice-error-illegal-state = This invoice can no longer be edited
invoice-product-picker-title = Select a product
invoice-product-picker-search = Search product…
invoice-product-picker-empty = No products
invoice-contact-picker-placeholder = Search contact…
invoice-contact-picker-empty = No contacts

# Story 5.2 — Validation & numérotation (TODO: traduction — fallback fr-CH via kesh-i18n)

# --- Story 5.3 — QR Bill PDF ---

invoice-pdf-title = Invoice
invoice-pdf-date = Date
invoice-pdf-due-date = Due date
invoice-pdf-number = Invoice number
invoice-pdf-origin-reference = Original invoice ref.
credit-note-pdf-title = Credit note
credit-note-pdf-number = Credit note number
invoice-pdf-ide = VAT ID
invoice-pdf-recipient = Recipient
invoice-pdf-description = Description
invoice-pdf-quantity = Qty
invoice-pdf-unit-price = Unit price
invoice-pdf-vat = VAT
invoice-pdf-line-total = Total
invoice-pdf-subtotal = Subtotal
invoice-pdf-total = Total
invoice-pdf-total-ttc = Total (incl. VAT)
invoice-pdf-payment-terms = Payment terms
invoice-pdf-qr-section-payment = Payment part
invoice-pdf-qr-section-receipt = Receipt
invoice-pdf-qr-account = Account / Payable to
invoice-pdf-qr-reference = Reference
invoice-pdf-qr-additional-info = Additional information
invoice-pdf-qr-payable-by = Payable by
invoice-pdf-qr-currency = Currency
invoice-pdf-qr-amount = Amount
invoice-pdf-qr-acceptance-point = Acceptance point
invoice-pdf-qr-separate-before-paying = Separate before paying in

invoice-pdf-error-invoice-not-validated = The invoice must be validated before generating a PDF.
invoice-pdf-error-invoice-not-pdf-ready = The invoice is not ready for PDF generation.
invoice-pdf-error-pdf-generation-failed = PDF generation failed. Please try again later.
invoice-pdf-error-popup-blocked = Pop-up blocked by the browser — please allow pop-ups to download the PDF.
invoice-pdf-error-missing-contact-address = Customer address is missing — fill it in the contact sheet.
invoice-pdf-error-missing-primary-bank-account = No primary bank account configured — add one in settings.

invoices-download-pdf = Download PDF
invoices-download-pdf-aria-label = Download invoice { $number } as PDF

error-invoice-not-validated = The invoice must be validated before generating a PDF.
error-invoice-too-many-lines-for-pdf = The invoice contains { $count } lines — the single-page A4 PDF cannot fit them all with the VAT summary. Reduce the number of lines or split the invoice.
error-pdf-generation-failed = PDF generation failed.
# Story 9-2a + Pass 1 code-review H1 — dedicated CSV variant.
error-csv-generation-failed = CSV generation failed.

# Story 5.4 — Invoice due dates
due-dates-title = Due dates
due-dates-link-aged = View aged balance
due-dates-link-reminders = View reminders
due-dates-filter-all = All
due-dates-filter-unpaid = Unpaid
due-dates-filter-overdue = Overdue
due-dates-filter-paid = Paid
due-dates-summary-unpaid = unpaid invoices
due-dates-summary-overdue = overdue
due-dates-search-label = Search
due-dates-contact-label = Contact
due-dates-contact-placeholder = All contacts
due-dates-due-before-label = Due before
due-dates-column-date = Date
due-dates-column-due-date = Due date
due-dates-column-contact = Customer
due-dates-column-total = Total
due-dates-column-payment-status = Status
due-dates-column-paid-at = Paid on
due-dates-export-button = Export CSV
due-dates-no-results = No invoices to display.
due-dates-result-suffix = result(s)

payment-status-paid = Paid
payment-status-unpaid = Unpaid
payment-status-overdue = Overdue

invoice-mark-paid-button = Mark as paid
invoice-mark-paid-dialog-title = Mark invoice as paid
invoice-mark-paid-dialog-body = Enter the date you received the payment.
invoice-mark-paid-date-label = Payment date
invoice-mark-paid-confirm = Confirm payment
invoice-mark-paid-success = Invoice marked as paid
invoice-unmark-paid-button = Unmark paid
invoice-unmark-paid-dialog-title = Unmark paid
invoice-unmark-paid-dialog-body = This invoice will be unpaid again. Useful to fix a mistake. Continue?
invoice-unmark-paid-confirm = Unmark
invoice-unmark-paid-success = Payment mark removed
invoice-detail-paid-at-label = Paid on

invoice-error-paid-at-required = Payment date required
invoice-error-paid-at-before-invoice-date = Payment date cannot be before the invoice date
invoice-error-mark-paid-not-validated = Only validated invoices can be marked as paid
invoice-error-already-unpaid = This invoice is not marked as paid

echeancier-csv-header-number = Number
echeancier-csv-header-date = Date
echeancier-csv-header-due-date = Due date
echeancier-csv-header-contact = Customer
echeancier-csv-header-total = Total
echeancier-csv-header-payment-status = Payment status
echeancier-csv-header-paid-at = Paid on
echeancier-export-error-too-large = Too many results (> { $limit }). Please refine your filters (e.g. date range or payment status) before exporting.
invoice-pdf-error-contact-missing = The contact linked to this invoice was not found.
invoice-pdf-error-no-primary-bank = No primary bank account is configured for this company.
invoice-pdf-error-company-address-empty = Company address is empty — please fill it in before generating a PDF.
invoice-pdf-error-client-address-required = The client address is required to generate the PDF.
invoice-pdf-error-client-address-empty = The client address is empty — please fill it in before generating a PDF.

common-loading = Loading…
common-previous = Previous
common-next = Next
common-cancel = Cancel
common-error = Unexpected error

invoice-pdf-error-not-found = Invoice not found.
invoice-pdf-error-generic = Error downloading the PDF.
invoice-pdf-error-empty = Received PDF is empty.

# Story 2.6 — Onboarding: Invoice Settings Pre-fill
config-incomplete-title = Configuration incomplete
config-incomplete-link = Configure invoicing accounts
invoice-settings-required = Please configure the invoicing accounts in settings first

# === Story 3.7 — Fiscal Years (EN-CH) ===

fiscal-year-title = Fiscal Years
fiscal-year-list-empty = No fiscal years.
fiscal-year-create-button = New fiscal year
fiscal-year-name-label = Name
fiscal-year-start-date-label = Start date
fiscal-year-end-date-label = End date
fiscal-year-status-label = Status
fiscal-year-status-open = Open
fiscal-year-status-closed = Closed
fiscal-year-rename-button = Rename
fiscal-year-close-button = Close
fiscal-year-close-confirmation-title = Close this fiscal year?
fiscal-year-close-confirmation-body = You are about to close fiscal year "{ $name }". While it stays closed, no entry, invoice, or payment can be recorded for this period; only an administrator can reopen it (with a logged reason). Confirm?
fiscal-year-close-confirmation-action = Close
fiscal-year-created = Fiscal year created successfully.
fiscal-year-renamed = Fiscal year renamed.
fiscal-year-closed = Fiscal year closed.
# Story 14-2 — reopening a closed fiscal year (Admin, reason, audit, LIFO guard)
fiscal-year-reopen-button = Reopen
fiscal-year-reopen-confirmation-title = Reopen this fiscal year?
fiscal-year-reopen-confirmation-body = You are about to reopen fiscal year "{ $name }". It will become editable again (entry posting) until it is closed anew. A reason is required and will be kept in the audit trail.
fiscal-year-reopen-motif-label = Reason for reopening
fiscal-year-reopen-confirmation-action = Reopen fiscal year
fiscal-year-reopened = Fiscal year reopened.
fiscal-year-reopen-blocked-later-closed = First reopen fiscal year "{ $name }", which is more recent and still closed.
error-fiscal-year-reopen-motif-empty = The reason for reopening is required.
error-fiscal-year-reopen-motif-too-long = The reason for reopening is too long (500 characters maximum).
error-fiscal-year-already-open = This fiscal year is already open.
error-fiscal-year-reopen-blocked = Cannot reopen: a later fiscal year is closed; reopen it first.
error-fiscal-year-overlap = This fiscal year overlaps with an existing one.
error-fiscal-year-name-duplicate = A fiscal year with this name already exists.
error-fiscal-year-name-empty = The fiscal year name is required.
error-fiscal-year-name-too-long = The fiscal year name is too long (50 characters maximum).
error-fiscal-year-dates-invalid = Invalid dates — the end date must be strictly after the start date.
error-fiscal-year-already-closed = This fiscal year is already closed.
error-fiscal-year-conflict = Fiscal year conflict (name or start date already in use).
error-fiscal-year-missing = First create a fiscal year in Settings → Fiscal Years.
error-fiscal-year-closed-for-date = The fiscal year covering this date is closed. Check the entered date or your fiscal years.
go-to-settings = Open Settings
settings-fiscal-years-link = Create, rename, or close your company fiscal years.

# Story 14-4 — opening balance sheet (starting balances, accounting migration)
opening-balances-title = Opening balances
opening-balances-intro = Enter the balances of your balance-sheet accounts carried over from your previous accounting system. A balanced opening entry will be generated as of { $date } (first day of fiscal year "{ $name }"). Post your accumulated retained earnings to your retained-earnings account to balance the entry.
opening-balances-account = Account
opening-balances-debit = Debit
opening-balances-credit = Credit
opening-balances-total-debit = Total debits
opening-balances-total-credit = Total credits
opening-balances-diff = Difference
opening-balances-generate = Generate opening entry
opening-balances-generating = Generating…
opening-balances-success = Opening entry generated.
opening-balances-entry-description = Opening balance sheet — starting balances
opening-balances-locked-no-fiscal-year = No fiscal year yet: first create a fiscal year (Settings → Fiscal Years) to enter your opening balances.
opening-balances-locked-first-year-closed = The first fiscal year "{ $name }" is closed: an administrator must reopen it before opening balances can be entered.
opening-balances-locked-already-has-entries = The company already contains journal entries: the opening balance sheet is locked. Correct the opening entry directly in the journal, or delete all entries to start over.
opening-balances-goto-journal = Open the journal
opening-balances-goto-balance-sheet = View the balance sheet
opening-balances-status-error = Could not load the opening balances status.
opening-balances-retry = Retry
opening-balances-empty-grid = No active, postable balance-sheet account in your chart of accounts — create or reactivate your asset and liability accounts (Chart of accounts) before entering opening balances.
error-opening-balances-no-fiscal-year = No fiscal year yet: create a fiscal year before entering opening balances.
error-opening-balances-first-year-closed = The first fiscal year is closed: reopen it before entering opening balances.
error-opening-balances-already-has-entries = The company already contains journal entries: the opening balance sheet can no longer be generated. Correct the opening entry via the journal.
error-opening-balances-non-balance-account = The opening balance sheet may only touch balance-sheet accounts (assets and liabilities) — remove income and expense accounts.


# --- Story 8-1b — CAMT.053 bank import ---
bank-import-errors-too-large = File too large. Maximum size: 10 MiB.
bank-import-errors-malformed-xml = Malformed or truncated XML file. Please check the bank export.
bank-import-errors-unsupported-version = Unsupported CAMT.053 version. Accepted versions: 001.04 and 001.08.
bank-import-errors-missing-field = A required field is missing from the CAMT.053 file.
bank-import-errors-invalid-amount = An amount in the file is invalid.
bank-import-errors-invalid-date = A date in the file is invalid.
bank-import-errors-balance-mismatch = The closing balance does not match the sum of transactions. Tick "Confirm despite mismatch" to import anyway.
bank-import-errors-unsupported-currency = Unsupported currency. Only Swiss francs (CHF) are accepted in this version.
bank-import-errors-no-matching-statement = No statement in the file matches the selected bank account.
bank-import-errors-duplicate-file = This file has already been imported for this company.
bank-import-errors-bank-account-not-found = Bank account not found.
bank-import-errors-parse-failed = The CAMT.053 file could not be parsed.

bank-import-warnings-balance-mismatch = Closing balance inconsistent.
bank-import-warnings-unsupported-currency = Unsupported currency in v0.1.
bank-import-warnings-ignored-statements = Some statements in the file do not match the selected account and will be ignored.
# Story 8-3 — duplicate detection + partial commit
bank-import-warnings-duplicate-file = This file has already been imported.
bank-import-warnings-duplicate-lines-summary = transactions overlap a previous import.
bank-import-warnings-invalid-lines-summary = invalid lines detected in the CSV.
bank-import-warnings-invalid-lines-truncated = First 100 errors shown (cap reached).
bank-import-warnings-encoding-mismatch = Detected encoding differs from profile.

bank-import-labels-page-title = CAMT.053 bank import
bank-import-labels-bank-account-selector = Target bank account
bank-import-labels-drop-zone = Drop your CAMT.053 file here or click to browse
bank-import-labels-preview-title = Preview
bank-import-labels-confirm-import = Confirm import
bank-import-labels-cancel = Cancel
bank-import-labels-confirm-balance-mismatch = Import despite balance mismatch
# Story 8-3 — confirm flags + KF #70
bank-import-labels-confirm-duplicate-file = Import despite duplicate file
bank-import-labels-confirm-duplicate-lines = Duplicate handling
bank-import-labels-confirm-duplicate-lines-skip = Skip duplicates (default)
bank-import-labels-confirm-duplicate-lines-import = Import anyway
bank-import-labels-confirm-partial-import = Import valid lines anyway
bank-import-labels-confirm-encoding-mismatch = Import with detected encoding
bank-import-labels-bank-profile-selector = CSV bank profile
bank-import-labels-bank-profile-auto-matched = auto-detected
# L6 / M8 (Pass 1 review)
bank-import-labels-bank-profile-auto-detect-placeholder = Auto-detect
bank-import-info-bank-csv-profile-auto-matched = Bank profile auto-detected from the filename.
bank-import-info-bank-csv-multiple-profile-matches = Multiple profiles match the filename ; the first one was selected.
bank-import-errors-no-valid-lines-to-commit = No valid lines to import in the CSV.
bank-import-labels-list-title = Previous imports
bank-import-labels-import-success = Import successful.
bank-import-labels-empty = No bank imports.

# Story 8-2 — bank-csv + bank-profile keys
bank-import-csv-errors-no-profile-match = No bank profile matches this file.
bank-import-csv-errors-unsupported-encoding = File encoding not supported (UTF-8 or ISO-8859-1 expected).
bank-import-csv-errors-encoding-mismatch = Detected encoding differs from profile. Confirm via confirmEncodingMismatch=true.
bank-import-csv-errors-partial-failure = Some CSV lines could not be parsed.
bank-import-csv-errors-profile-invalid = Bank profile invalid.
bank-import-csv-errors-profile-duplicate = A profile with this bank name already exists.
bank-import-csv-errors-profile-misconfigured = Bank profile misconfigured.
bank-import-csv-errors-empty-file = Empty CSV file or no data rows.
bank-import-csv-errors-invalid-date = Invalid date in a CSV row.
bank-import-csv-errors-invalid-amount = Invalid amount in a CSV row.
bank-import-csv-errors-ambiguous-debit-credit = Debit AND credit non-empty on the same row.
bank-import-csv-errors-empty-mandatory-field = Mandatory field empty.
bank-import-csv-errors-row-too-short = Row too short (missing columns).
bank-import-csv-warnings-profile-auto-matched = Profile auto-matched.
bank-import-csv-warnings-multiple-profile-matches = Multiple profiles match this filename, the most recent was used.
bank-import-csv-warnings-encoding-mismatch = Detected encoding differs from profile.
bank-import-errors-unsupported-format = File format not supported (CAMT.053 XML or CSV expected).
bank-import-profile-labels-page-title = CSV bank profiles
bank-import-profile-labels-page-title-new = New bank profile
bank-import-profile-labels-page-title-edit = Edit bank profile
bank-import-profile-labels-bank-name = Bank name
bank-import-profile-labels-filename-pattern = Filename pattern (regex)
bank-import-profile-labels-filename-pattern-help = Regex case-sensitive (use `(?i)` for case-insensitive)
bank-import-profile-labels-date-format = Date format (chrono)
bank-import-profile-labels-decimal-separator = Decimal separator
bank-import-profile-labels-field-separator = Field separator
bank-import-profile-labels-encoding = Encoding (optional)
bank-import-profile-labels-header-row-count = Header rows count (0-5)
bank-import-profile-labels-column-mapping = Column mapping (0-indexed)
bank-import-profile-labels-use-debit-credit-split = Separate debit/credit columns
bank-import-profile-labels-create = Create
bank-import-profile-labels-update = Update
bank-import-profile-labels-edit = Edit
bank-import-profile-labels-delete = Delete
bank-import-profile-labels-confirm-delete = Delete this profile?
bank-import-profile-labels-new-profile = New profile
bank-import-profile-labels-no-profiles = No bank profile configured.
bank-import-profile-errors-bank-name-required = Bank name is required.
bank-import-profile-errors-bank-name-duplicate = A profile with this name already exists.
bank-import-profile-errors-column-mapping-xor-violation = Choose `amount` OR `debit_credit_split`, not both.
bank-import-profile-errors-date-format-invalid = Invalid chrono date format.
bank-import-profile-errors-regex-invalid = Invalid filename_pattern regex.
bank-import-profile-errors-separators-equal = Field and decimal separators must be different.

# Story 8-4 (FR44) — Automatic bank reconciliation.
reconciliation-page-title = Reconciliation
reconciliation-page-subtitle = Automatic match proposals transaction ↔ invoice.
reconciliation-labels-loading = Loading proposals…
reconciliation-labels-empty = No transactions awaiting reconciliation.
reconciliation-labels-no-account = No bank account configured.
reconciliation-labels-account-select = Bank account
reconciliation-labels-no-candidate = No match
reconciliation-labels-success-suffix = operation(s) succeeded.
reconciliation-labels-failed = Partial failures
reconciliation-cols-tx-date = Date
reconciliation-cols-tx-amount = Amount
reconciliation-cols-tx-counterparty = Counterparty
reconciliation-cols-candidate = Candidate
reconciliation-cols-score = Score
reconciliation-actions-accept = Accept
reconciliation-actions-reject = Reject
# H8 Pass 1 code review — 8 canonical keys AC #61.
reconciliation-labels-validate-selected = Validate selection
reconciliation-labels-reject-selected = Reject selection
reconciliation-labels-score = Score
reconciliation-errors-account-locked = Bank account is being reconciled by another user. Please retry in a few seconds.
reconciliation-errors-already-reconciled = This transaction is already reconciled.
reconciliation-errors-invoice-not-eligible = This invoice is not eligible for reconciliation.
reconciliation-toast-accept-success = { $count } transaction(s) reconciled successfully.
reconciliation-toast-reject-success = { $count } transaction(s) rejected successfully.

# Story 8-5a-base FR45 — Manual reconciliation.
reconciliation-manual-button-label = Assign manually
reconciliation-manual-modal-title = Manual reconciliation
reconciliation-manual-counterparty-label = Counterparty account
reconciliation-manual-description-label = Description
reconciliation-manual-bank-account-not-configured = The bank account is not configured. Link a chart-of-accounts entry under /bank-accounts.
reconciliation-manual-value-date-label = Value date
reconciliation-manual-submit = Assign
reconciliation-manual-error-no-proposal = No transaction selected
reconciliation-manual-error-counterparty-required = Counterparty account required
reconciliation-manual-error-description-too-long = Description too long (max { $max } characters)
reconciliation-manual-description-placeholder = Bank fees May

# Story 8-5a-bis FR48 — split aggregated transaction.
reconciliation-split-button-label = Split
reconciliation-split-modal-title = Split transaction
reconciliation-split-balance-indicator = Balance
reconciliation-split-error-imbalance = The split does not balance the transaction amount.

reconciliation-cols-actions = Actions

# Story 8-5a-zero — `bank_account.journal_account_id` link configuration.
bank-accounts-labels-page-title = Bank accounts
bank-accounts-labels-page-subtitle = Link each bank account to a chart-of-accounts entry (typical class 1: 1020 Cash, 1030 Bank).
bank-accounts-labels-bank-name = Bank
bank-accounts-labels-iban = IBAN
bank-accounts-labels-journal-account-id = Linked ledger account
bank-accounts-labels-not-configured = Not configured
bank-accounts-labels-empty = No bank accounts configured.
bank-accounts-labels-loading = Loading…
bank-accounts-actions-link-account = Link to chart of accounts
bank-accounts-actions-unlink-account = Unlink
bank-accounts-actions-cancel = Cancel
bank-accounts-actions-submit = Link
bank-accounts-errors-account-not-found = Ledger account not found.
bank-accounts-errors-invalid-account-type = Invalid account type (Asset or Liability required).
# Story v014-1 — CRUD bank_accounts post-onboarding
bank-accounts-errors-has-transactions = Bank account has transactions — archive refused to preserve accounting audit.
bank-accounts-errors-cannot-archive-primary = The primary account cannot be archived while another non-archived account exists. First set another account as primary, then archive this one.
bank-accounts-errors-onboarding-not-complete = Onboarding must be completed (step 7) before bank accounts can be managed.
# Story v014-1 — CRUD UI labels & actions (F3 Pass 1 code review parity DE/IT/EN)
bank-accounts-actions-create = New bank account
bank-accounts-actions-edit = Edit
bank-accounts-actions-archive = Archive
bank-accounts-actions-confirm-archive = Archive
bank-accounts-actions-show-archived = Show archived
bank-accounts-actions-hide-archived = Hide archived
bank-accounts-actions-submit-create = Create
bank-accounts-actions-submit-update = Save
bank-accounts-labels-balance = Balance
bank-accounts-labels-balance-unavailable = Balance unavailable (link to chart of accounts)
bank-accounts-labels-qr-iban = QR-IBAN (optional)
bank-accounts-labels-is-primary = Primary account
bank-accounts-labels-primary-badge = Primary
bank-accounts-labels-archived-badge = Archived
bank-accounts-confirm-archive = Confirm archiving this bank account? This action is irreversible in v0.1.
bank-accounts-tooltip-journal-account = Links this bank account to a ledger account (typically 1020 Cash, 1030 Bank). Allows automatic reconciliation to create entries on the right account, and balance display on the homepage. Multiple accounts: if you have several distinct current accounts (BCV + PostFinance), link to a specific sub-account (1030.001 BCV CHF), not the parent 1030.
bank-accounts-toast-create-success = Bank account created.
bank-accounts-toast-update-success = Bank account updated.
bank-accounts-toast-archive-success = Bank account archived.
# Story v014-1 — Homepage widget bank accounts (F14)
homepage-bank-total-liquidity = Total liquidity
homepage-bank-total-partial = (linked accounts only)
homepage-bank-balance-unavailable = Balance unavailable — link to chart of accounts
homepage-bank-last-transaction = Last transaction
settings-bank-manage = Manage in Administration → Bank accounts
settings-bank-manage-hint = To add, edit or archive a bank account, use the dedicated page Administration → Bank accounts.
bank-accounts-toast-link-success = Bank account successfully linked to chart of accounts.
bank-accounts-toast-unlink-success = Bank account unlinked from chart of accounts.

# Story 8-5b — FR47 reconciliation rules.
reconciliation-rules-page-title = Reconciliation rules
reconciliation-rules-loading = Loading…
reconciliation-rules-labels-empty = No rule configured.
reconciliation-rules-labels-label = Label
reconciliation-rules-labels-match-type = Type
reconciliation-rules-labels-match-value = Value
reconciliation-rules-labels-counterparty-account = Counterparty account
reconciliation-rules-labels-priority = Priority
reconciliation-rules-labels-priority-hint = Lower value = higher priority (1-1000)
reconciliation-rules-labels-applied-count = Applied
reconciliation-rules-labels-status = Status
reconciliation-rules-labels-active = Active
reconciliation-rules-labels-archived = Archived
reconciliation-rules-match-type-counterparty-contains = Counterparty contains
reconciliation-rules-match-type-counterparty-exact = Counterparty exact
reconciliation-rules-match-type-reference-contains = Reference contains
reconciliation-rules-match-type-iban-exact = IBAN exact
reconciliation-rules-form-title-create = New rule
reconciliation-rules-form-title-edit = Edit rule
reconciliation-rules-actions-new = New rule
reconciliation-rules-actions-edit = Edit
reconciliation-rules-actions-create = Create
reconciliation-rules-actions-save = Save
reconciliation-rules-actions-cancel = Cancel
reconciliation-rules-actions-archive = Archive
reconciliation-rules-actions-deactivate = Deactivate
reconciliation-rules-actions-reactivate = Reactivate
reconciliation-rules-confirm-delete = Archive this rule? Already-applied entries are preserved.
reconciliation-rules-error-label-required = Label required
reconciliation-rules-error-match-value-required = Value required
reconciliation-rules-error-counterparty-required = Counterparty account required
reconciliation-rules-error-not-found = Rule not found.
reconciliation-rules-error-duplicate = An active rule already exists for this type/value combination.
reconciliation-rules-applied-badge = Rule
reconciliation-rules-applied-score-na = Auto

# === Story 9-1 — Accounting reports (34 keys) ===
# TODO official translation — basic translation (Pass 1 ECH-19)

reports-balance-sheet = Balance Sheet
reports-income-statement = Income Statement
reports-trial-balance = Trial Balance
reports-journals = Journals

reports-column-account-number = Account No.
reports-column-account-name = Account Name
reports-column-debit = Debit
reports-column-credit = Credit
reports-column-balance = Balance
reports-column-entry-date = Date
reports-column-description = Description

reports-section-assets = Assets
reports-section-liabilities = Liabilities
reports-section-equity = Equity
reports-section-revenues = Revenues
reports-section-expenses = Expenses

reports-total-assets = Total Assets
reports-total-liabilities = Total Liabilities
reports-total-equity = Total equity
reports-total-revenues = Total Revenues
reports-total-expenses = Total Expenses
reports-total-debit = Total Debit
reports-total-credit = Total Credit
reports-net-result = Net Result
reports-grand-total = Grand Total
# VAT report (Story 11-2)
reports-vat = VAT
reports-vat-column-rate = Rate
reports-vat-column-base-ht = Net turnover
reports-vat-column-vat-due = VAT due
reports-vat-total-base-ht = Total net turnover
reports-vat-recoverable = Recoverable VAT
reports-vat-balance = Balance
reports-vat-reconciliation-warning = The VAT return does not match the accounting entries (difference: { $delta }). Check validated entries modified manually.

reports-filter-period = Period
reports-filter-fiscal-year = Fiscal Year
reports-filter-journal = Journal
reports-button-generate = Generate

reports-error-no-entries-in-period = No entries in the selected period. Change the dates or pick a different fiscal year.
reports-error-period-out-of-fiscal-year = The selected period exceeds the fiscal year bounds. Pick a period between { $fyStart } and { $fyEnd }.
reports-error-no-fiscal-year-available = No fiscal year available. Create a fiscal year before generating reports.

reports-equity-result-section-title = Period result (before closing entries)
reports-equity-result-profit = Period profit
reports-equity-result-loss = Period loss
reports-retained-earnings = Retained earnings
reports-retained-earnings-calculated = Retained earnings (calculated)
reports-retained-earnings-loss = Accumulated loss
reports-trial-balance-period-note = The trial balance shows the movement of the period (per fiscal year). The per-account total is not comparable to the cumulative balance of the same account in the balance sheet (carry-forward from inception).

# Alerts + badges UI (2 — code review Pass 1 i18n leaks)
reports-equation-warning = ⚠️ Balance sheet equation unbalanced (verify source data).
reports-archived-label = archived

# Reports page — chrome (3 — code review Pass 1 i18n leaks)
reports-page-title = Accounting Reports
reports-instruction-select-and-generate = Select a fiscal year and click Generate.
reports-loading = Generating report…

# Story 9-2a — Export PDF & CSV (10 keys)
reports-export-pdf-button = Export PDF
reports-export-csv-button = Export CSV
# Story 21-7 — Aged receivables balance
reports-aged-balance = Aged balance
reports-aged-instruction = Aged balance as of today.
reports-aged-instruction-generate = Click Generate to display the aged balance as of today.
reports-aged-as-of = As of { $date }
reports-aged-empty = No open customer receivables.
reports-aged-col-contact = Customer
reports-aged-col-not-due = Not due
reports-aged-col-1-30 = 1-30 d
reports-aged-col-31-60 = 31-60 d
reports-aged-col-61-90 = 61-90 d
reports-aged-col-over-90 = 90+ d
reports-aged-col-total = Total
reports-aged-total-row = Grand total
reports-aged-link-due-dates = View due dates
reports-export-loading = Generating file…
reports-export-error-generic = Unable to export report. Check your connection and try again.
reports-filename-balance-sheet = balance-sheet
reports-filename-income-statement = income-statement
reports-filename-trial-balance = trial-balance
reports-filename-journals = journals
reports-filename-vat = vat-return
reports-filename-project-expenses = expenses-by-project
reports-filename-project-return = return-by-project
reports-pdf-header-period = Period
reports-pdf-empty-message = No entries in the selected period.

# Story 9-2b — Global ZIP export (data sovereignty) — 12 keys
nav-export-global = Global export
# Story 17-3b — full installation backup (.keshbackup, Admin)
nav-admin-backup = Full backup
admin-backup-page-title = Full installation backup
admin-backup-page-description = Downloads the entire installation (all companies, users and system data) into a single .keshbackup file, for migration or backup. Distinct from a single company's global export.
admin-backup-action-export = Export the entire installation
admin-backup-action-exporting = Exporting…
admin-backup-toast-success = Installation backup downloaded.
admin-backup-error-generic = Installation export failed. Please try again shortly.
admin-backup-page-hint-secret = The .keshbackup file contains sensitive data (credentials, tokens). Keep it in a safe place.
# Story 17-3d — full installation import / restore (.keshbackup, Admin)
nav-admin-restore = Restore / Import
admin-restore-page-title = Installation restore / import
admin-restore-page-description = Upload a .keshbackup file to replace the entire current installation (migration or restore). Destructive operation: a backup of the current state is created server-side before the import.
admin-restore-file-label = .keshbackup file to import
admin-restore-action-import = Import and replace the installation
admin-restore-action-importing = Importing…
admin-restore-confirm-title = Replace the entire installation?
admin-restore-confirm-body = This action will replace ALL data of the current installation. A backup of the current state will be created server-side before the import. You will be logged out and must log back in with the credentials of the imported instance.
admin-restore-confirm-cancel = Cancel
admin-restore-confirm-ok = Confirm replacement
admin-restore-toast-success = Import successful — you will be logged out.
admin-restore-error-version = This backup requires a newer version of Kesh ({ $src }) than the one installed ({ $bin }). Update Kesh before importing again.
admin-restore-error-schema = Backup schema incompatible with this version of Kesh (table { $table }).
admin-restore-error-invalid = Backup file invalid or corrupted. Make sure it is a .keshbackup file produced by Kesh.
admin-restore-error-generic = Import failed. The previous state of the installation was preserved.
export-global-title = Global export of your data
export-global-description = Export all your accounting data (accounts, journal entries, contacts, invoices, bank transactions) in CSV format inside a ZIP file. Use this export to archive, migrate to another software, or keep your data for 10 years (Swiss CO Art. 958f).
export-global-button = Start export
export-global-loading = Generating export…
export-global-success = Export downloaded.
export-global-error-generic = Could not generate the global export. Check your connection and try again.
export-global-filename-hint = The file will be downloaded as kesh-export-{ $companyShort }-{ $date }.zip
export-global-content-includes = The export contains: chart of accounts, fiscal years, journal entries, contacts, products, invoices, bank accounts, bank import history, transactions, active and historical VAT rates, invoice settings, reconciliation rules, bank import profiles, and a metadata.json manifest with SHA-256 hash of each file for integrity verification.
export-global-content-excludes = Does not contain: users (PII + passwords), session tokens, internal audit log, onboarding state (security and technical reasons).
export-global-souverainete-note = Your data belongs to you. Kesh keeps no copy of this export on its servers.
error-global-export-failed = The global export could not be generated. If the problem persists, please contact support.
error-admin-full-export-failed = The full installation export could not be generated. Please try again shortly; if the problem persists, contact support.
error-admin-full-import-failed = The installation import failed. The previous state was preserved (an automatic backup was created before the operation). Check the server logs, then try again.
error-invalid-backup-structure = The backup file is invalid or corrupted (unexpected structure or failed integrity check). Make sure it is a .keshbackup file produced by Kesh.
error-import-schema-mismatch = This backup's schema is incompatible with this version of Kesh. Update Kesh or use a compatible backup.
error-import-version-incompatible = This backup requires a newer version of Kesh than the one installed. Update Kesh before importing again.

# Story v011-5 — Self-service onboarding (12 UI keys + 2 error keys)
error-setup-required = Initial setup required. Create the administrator account via /setup.
error-setup-already-complete = The administrator account has already been created.
setup-welcome = Welcome to Kesh
setup-intro = To finish the installation, create the initial administrator account. This account will have full rights on your Kesh instance.
setup-username-label = Username
setup-username-placeholder = admin
setup-username-required = Username is required.
setup-password-label = Password
setup-password-min = At least 12 characters.
setup-password-confirm-label = Confirm password
setup-password-mismatch = Passwords do not match.
setup-email-label = Email (recommended)
setup-email-hint = Allows resetting your password by email if you forget it.
setup-email-invalid = Invalid email format.
setup-submit = Create administrator account
setup-error-already-complete = The administrator account has already been created. You will be redirected to the login page.
setup-error-rate-limit = Too many attempts. Try again in a few minutes.

# === Story 17-2b — API keys (PAT) frontend (36 keys) ===
# Settings → link
settings-api-keys-title = API keys
settings-api-keys-manage = Manage
settings-api-keys-hint = Create API access keys for your integrations (external AI, scripts, third-party software).
# API keys page — labels
api-keys-labels-page-title = API keys
api-keys-labels-page-subtitle = Create API access keys for your integrations (external AI, scripts, third-party software). Present the key via the "Authorization: Bearer" header.
api-keys-labels-name = Name
api-keys-labels-name-placeholder = e.g. Accounting script, AI agent…
api-keys-labels-scope = Scope
api-keys-labels-scope-read = Read-only
api-keys-labels-scope-read-write = Read-write
api-keys-labels-expires = Expiry (optional)
api-keys-labels-expires-hint = Leave empty for a permanent key.
api-keys-labels-created-at = Created on
api-keys-labels-last-used = Last used
api-keys-labels-never-used = Never used
api-keys-labels-status = Status
api-keys-labels-status-active = Active
api-keys-labels-status-expires = Active (expires on { $date })
api-keys-labels-status-revoked = Revoked on { $date }
api-keys-labels-status-expired = Expired on { $date }
api-keys-labels-empty = No API keys. Create one for your integrations.
api-keys-labels-loading = Loading…
api-keys-labels-secret-created = Key "{ $name }" created.
api-keys-labels-secret-warning = Copy this key now: it will never be shown again.
# Actions
api-keys-actions-create = New key
api-keys-actions-submit-create = Create key
api-keys-actions-cancel = Cancel
api-keys-actions-copy = Copy
api-keys-actions-close = Close
api-keys-actions-revoke = Revoke
api-keys-actions-confirm-revoke = Revoke
# Confirmation
api-keys-confirm-revoke = Revoke this key? Any integration using it will immediately stop working. This action is irreversible.
# Errors
api-keys-errors-name-required = The key name is required.
api-keys-errors-name-too-long = The key name is too long (255 characters maximum).
api-keys-errors-conflict = The key changed in the meantime — list reloaded, please retry.
# Toasts
api-keys-toast-create-success = API key created.
api-keys-toast-copied = Key copied to clipboard.
api-keys-toast-copy-failed = Copy failed — please select and copy manually.
api-keys-toast-revoke-success = Key revoked.

# Story 17-4b — Password recovery by email (backend rendering, DC10)
error-smtp-send-failed = Email delivery failed. Please try again shortly.

# Story 20-3b1 — invoice sending by email
error-smtp-not-configured = Email sending is not configured on this instance (KESH_SMTP_* variables).
error-contact-email-missing = The invoice contact has no email address. Add it on the contact card.
error-invoice-email-empty-content = The email subject and body cannot be empty.
error-invoice-due-date-before-date = The due date cannot be earlier than the invoice date
error-contact-archived = The invoice's contact is archived. Reactivate it before sending the invoice by email.
error-email-sent-invoice-gone = The email was delivered to the contact, but the invoice was deleted in the meantime — it could not be marked as sent. Do not resend the email.
error-company-email-invalid = The company email address is not valid.
error-invalid-or-expired-token = Invalid or expired password reset link.
email-password-reset-subject = Reset your Kesh password
email-password-reset-body =
    You requested a reset of your Kesh password.
    Open the following link to choose a new password (valid for { $ttlMinutes } minutes):
    { $resetUrl }
    If you did not request this, please ignore this email.

# Story 17-4d — Password recovery (public frontend pages)
auth-recovery-forgot-title = Forgot password
auth-recovery-forgot-intro = Enter your username or email address. If an account matches, you will receive a reset link.
auth-recovery-identifier-label = Username or email
auth-recovery-submit = Send reset link
auth-recovery-success-generic = If an account matches this identifier, an email containing a reset link has just been sent to it. The link is valid for 30 minutes.
auth-recovery-error-rate-limit = Too many attempts. Try again in a few minutes.
auth-recovery-error-network = Unable to reach the server. Check your connection.
auth-recovery-error-unavailable = Password reset by email is not available. Contact your administrator.
auth-recovery-error-server = Server error. Try again later.
auth-recovery-back-to-login = Back to sign in
auth-recovery-reset-title = New password
auth-recovery-reset-intro = Choose your new password.
auth-recovery-new-password-label = New password
auth-recovery-password-confirm-label = Confirm password
auth-recovery-password-min = At least 12 characters.
auth-recovery-password-mismatch = Passwords do not match.
auth-recovery-reset-submit = Reset password
auth-recovery-reset-success = Your password has been reset. You can now sign in.
auth-recovery-invalid-link = This reset link is invalid or has expired. Make a new request to receive a new link.
auth-recovery-request-new-link = Make a new request
auth-recovery-login-cta = Sign in

# Story 12.2 — factures fournisseurs (#191)
supplier-invoices-title = Supplier invoices

# Story 12.3 — paiements pain.001 (#191)
payment-batches-title = Supplier payments

# Story 20-3b2 — invoice sending by email (UI)
common-save = Save
common-edit = Edit
error-unexpected = Unexpected error.
invoice-send-email-button = Send by email
invoice-resend-email-button = Resend by email
invoice-send-email-smtp-tooltip = Email sending is not configured (KESH_SMTP_* variables) — see the administrator manual.
invoice-send-email-title = Send the invoice by email
invoice-send-email-to-label = Recipient
invoice-send-email-to-missing = The contact has no email address — add it on the contact page.
invoice-send-email-subject-label = Subject
invoice-send-email-body-label = Message
invoice-send-email-confirm = Send the email
invoice-send-email-success = Invoice sent by email
invoice-send-email-error-empty = The email subject and body cannot be empty.
invoice-detail-emailed-at-label = Sent on
contact-form-language = Correspondence language
contact-form-language-inherited = Inherited (instance language)
contact-form-salutation = Salutation
contact-salutation-neutre = Neutral
contact-salutation-monsieur = Mr
contact-salutation-madame = Ms
settings-field-company-email = Email (reply address)
settings-company-email-help = Reply-To address of invoices sent by email. Empty = no reply address.
settings-company-email-invalid = Invalid email address.
settings-company-email-saved = Company email saved
settings-company-email-conflict = Version conflict — data reloaded, please try again.
settings-company-email-conflict-reload-failed = Version conflict and reload failed — reload the page.

# --- Debtor reminders (Story 21-4, #231) ---
dunning-title = Debtor reminders
dunning-subtitle = Configure reminder levels, delays and reminder fees.
dunning-load-error = Unable to load reminder settings.
dunning-grace-heading = Grace period
dunning-grace-help = Days after the due date before the 1st reminder becomes eligible.
dunning-grace-label = Grace (days)
dunning-grace-save = Save
dunning-grace-saved = Grace period saved.
dunning-levels-heading = Reminder levels
dunning-level-new = Add a level
dunning-empty = No level configured — reminders are disabled.
dunning-col-level = Level
dunning-col-delay = Delay (days)
dunning-col-fee = Fee (CHF)
dunning-col-actions = Actions
dunning-edit = Edit
dunning-delete = Delete
dunning-example-heading = Projected schedule
dunning-example-line = Reminder { $level } proposed { $days } days after the due date
dunning-cgv-hint = Reminder fees are only due with a contractual basis (T&Cs). They are not included in the QR of the attached invoice.
dunning-delay-label = Delay (days)
dunning-delay-help = Days since the previous step (due date + grace for the 1st).
dunning-fee-label = Fee (CHF)
dunning-form-submit = Save
dunning-form-cancel = Cancel
dunning-form-error = Save failed.
dunning-form-error-delay = The delay must be a positive integer.
dunning-form-error-fee = The fee must be a valid amount.
dunning-delete-confirm-body = Delete this reminder level? The following levels will be renumbered.
dunning-delete-confirm-action = Delete
dunning-created = Reminder level added.
dunning-updated = Reminder level updated.
dunning-deleted = Reminder level deleted.
dunning-conflict = The level was changed in the meantime, reloaded.
settings-dunning-link = Configure reminder levels (delays and fees), the grace period, and customise the reminder e-mail texts per level.
email-templates-type-invoice_send = Invoice sending
email-templates-type-invoice_reminder = Payment reminder
email-templates-level-generic = Generic
email-templates-level-n = Reminder { $n }
email-templates-type-label = Type
email-templates-level-label = Level

# Story 21-6b — Reminders page (sending debtor reminders)
reminders-page-title = Reminders
reminders-forbidden = Access restricted to accountants and administrators.
reminders-empty = No invoice to remind.
reminders-level-name = Reminder { $level }
reminders-level-next = Next: reminder { $level }
reminders-last-sent = last on { $date }
reminders-select-invoice = Select { $inv }
reminders-selected-count = { $n } selected
reminders-batch-cap = Maximum { $cap } invoices per batch.
reminders-batch-send = Send selected reminders
reminders-sending = Sending…
reminders-saving = Saving…
reminders-badge-no-email = no e-mail
reminders-badge-terminal = Last level reached
reminders-batch-accepted = { $n } reminder(s) sent.
reminders-batch-failed = { $n } failure(s):
reminders-send-title = Send a reminder
reminders-send-open = Send a reminder
reminders-send-level-label = Reminder level
reminders-send-to-label = Recipient
reminders-send-no-recipient = The contact has no e-mail address.
reminders-send-subject-label = Subject
reminders-send-body-label = Message
reminders-send-empty = Subject and body cannot be empty.
reminders-send-confirm = Send the reminder
reminders-send-success = Reminder sent
reminders-manual-title = Record a manual reminder
reminders-manual-open = Manual reminder
reminders-manual-body = Record a reminder already sent outside Kesh (letter, registered mail). No e-mail will be sent.
reminders-manual-level-label = Reminder level
reminders-manual-date-label = Send date
reminders-manual-date-required = Send date required
reminders-manual-date-future = The send date cannot be in the future
reminders-manual-note-label = Note (optional)
reminders-manual-confirm = Record
reminders-manual-success = Manual reminder recorded
reminders-error-invoice-not-found = Invoice not found
reminders-error-invoice-not-validated = Invoice not validated
reminders-error-invoice-already-paid = Invoice already paid
reminders-error-dunning-paused = Reminders paused
reminders-error-no-next-level = Last level reached
reminders-error-contact-archived = Contact archived
reminders-error-contact-email-missing = Contact without e-mail address
reminders-error-content-empty = Reminder template empty
reminders-error-content-too-long = Reminder content too long
reminders-error-not-pdf-ready = Invoice not printable as PDF
reminders-error-rate-limited = Send limit reached
reminders-error-database-error = Technical error
reminders-error-smtp-failed = E-mail sending failed
reminders-error-sent-but-gone = E-mail sent, but the invoice vanished in the meantime (not recorded)
reminders-error-sent-not-recorded = E-mail sent, but not recorded (technical error)
reminders-error-unknown = Failure ({ $code })
# Story 21-6c — History & pause on the invoice detail page
reminders-history-title = Reminder history
reminders-history-empty = No reminder sent.
reminders-history-col-date = Date
reminders-history-col-level = Level
reminders-history-col-channel = Channel
reminders-history-col-recipient = Recipient
reminders-history-col-fee = Fee
reminders-history-channel-email = Email
reminders-history-channel-manual = Manual
reminders-history-cancelled-at = Cancelled on { $date }
reminders-pause-button = Pause reminders
reminders-resume-button = Resume reminders
reminders-pause-title = Pause reminders
reminders-pause-body = This invoice's automatic reminders are paused until resumed. You can note the reason (dispute, arrangement).
reminders-pause-note-label = Reason (optional)
reminders-pause-confirm = Pause
reminders-pause-submitting = Pausing…
reminders-pause-success = Reminders paused
reminders-resume-success = Reminders resumed
reminders-error-not-paused = This invoice is no longer paused.
reminders-link-due-dates = View due dates
reminders-link-aged = View aged balance
